version: '3.8'

services:
  frontend_app:
    build: . 
    container_name: frontend_app
    restart: always
    
    ports:
      - "80:3000" 

    environment:
      - REACT_APP_API_URL=http://184.72.212.15 
      - NODE_ENV=production
