version: '3.8'

services:
  uptime-kuma:
    container_name: uptime_kuma_web
    image: louislam/uptime-kuma:latest
    restart: always
    
    ports:
      - "80:3001"
      
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:
